{% set name = "mmengine" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mmengine-{{ version }}.tar.gz
  sha256: 68a8477c431c8590b44c545f532a883ad98fd3745be92f30906e03537a17e5e7

build:
  noarch: python
  script: MMENGINE_LITE=1 {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - addict
    - numpy
    - regex  # should be windows only
    - rich
    - termcolor
    - packaging
    - python >=3.7
    - pyyaml
    - yapf

test:
  imports:
    - mmengine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-mmlab/mmengine
  summary: Engine of OpenMMLab projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
