{% set name = "mmengine" %}
{% set version = "0.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mmengine-{{ version }}.tar.gz
  sha256: ffdce8485e73532d23e82658828e22651135005b0c19a417fa5391f41123c9ce

build:
  noarch: python
  script: MMENGINE_LITE=1 {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - addict
    - numpy
    - regex  # should be windows only
    - rich
    - termcolor
    - packaging
    - python >=3.7
    - pyyaml
    - yapf

test:
  imports:
    - mmengine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-mmlab/mmengine
  doc_url: https://mmengine.readthedocs.io
  dev_url: https://github.com/open-mmlab/mmengine
  summary: Engine of OpenMMLab projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
