{% set name = "mmengine" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mmengine-{{ version }}.tar.gz
  sha256: d3194b1f2e091a8b0b300c145e54b9230514a4d4a9eed49676ac8cb173aba5ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - addict
    - matplotlib-base
    - numpy
    - opencv >=3
    - regex  # should be windows only
    - rich
    - termcolor
    - python >=3.7
    - pyyaml
    - yapf

test:
  imports:
    - mmengine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-mmlab/mmengine
  summary: Engine of OpenMMLab projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
