{% set name = "mmengine" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mmengine-{{ version }}.tar.gz
  sha256: 2da72c4e499656333f0acfcf3d80fb237a86adad3979bfb279798741153feefb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - addict
    - matplotlib-base
    - numpy
    - opencv >=3
    - regex  # should be windows only
    - rich
    - termcolor
    - python >=3.7
    - pyyaml
    - yapf

test:
  imports:
    - mmengine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-mmlab/mmengine
  summary: Engine of OpenMMLab projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
