{% set name = "mmengine" %}
{% set version = "0.10.6" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mmengine-{{ version }}.tar.gz
  sha256: e9f27378cfcefb96c00ae281ab1d8440aa92e9f49bb841f3bea0bca3519a8ba0

build:
  noarch: python
  script: MMENGINE_LITE=1 {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - addict
    - numpy
    - regex  # should be windows only
    - rich
    - termcolor
    - packaging
    - python >={{ python_min }}
    - pyyaml
    - yapf

test:
  imports:
    - mmengine
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-mmlab/mmengine
  doc_url: https://mmengine.readthedocs.io
  dev_url: https://github.com/open-mmlab/mmengine
  summary: Engine of OpenMMLab projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
